development: &default
  adapter: postgresql
  database: info-kiosk_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: info-kiosk_test

  production:
  <<: *default
  database: info-kiosk_production
  username: info-kiosk
  password: <%= ENV['INFO-KIOSK_DATABASE_PASSWORD'] %>
