default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  secret_key_base: 'ed90b9b6b9ce817f48d240cd815c103e3bef272fdc96563458b523ac1b3ff4ca39bc195eeae3fc92b841b53bf7d8862782bbeb21695b46d352a319437c6d7680'

test:
  <<: *default

staging:
  <<: *default

production:
  <<: <%= ENV["SECRET_KEY_BASE"]

SMTP_ADDRESS=
SMTP_DOMAIN=
SMTP_PASSWORD=
SMTP_USERNAME=
EMAIL_RECIPIENTS=
ASSETS_VERSION=
ASSET_HOST=
